#!/usr/bin/env bash
# generating ssh key pairs

# Generate RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -C "school" -f school

# Add passphrase "betty" to the private key
echo "betty" | ssh-keygen -p -P "" -N "" -f school
